### ISSUE TITLE
recovery.py

### ISSUE THREAD

**Issue by codeall9** [eric0324/UNIX_final_project#18]
line 93&75
def vim() 
cmd = "cp -p" + path[1] + _"/vim ~/.vimrc"_

def git()
cmd = "cp -p" + path[1] + _"/git ~/.gitconfig"_

**Comment by codeall9** [comment]
line 108
cmd = "git checkout " + argv[2] + " " + argv[1]
當前目錄不是備份目錄的話，應該會有問題

**Comment by eric0324** [comment]
上面兩個 vim 和 git 沒設定，不會有目錄嗎？有點久沒初始設定，不確定。

108 行已經修正了，但是還沒測試

**Comment by codeall9** [comment]
目前備份目錄裡不會有其他目錄
.vimrc備份後的名字應該叫vim
.gitconfig備份後的名字應該叫git (backup.py 也一樣的問題)

**Comment by eric0324** [comment]
我指的是環境下的，不是備份的

然後.gitconfig 是一個 git 的檔案，直接取那樣比較快，不用名字換來換去

**Comment by eric0324** [comment]
已經修正！
